import "./globals.css";
import ApiUploadProvider from "@/commons/providers/api-upload-provider";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { ReactQueryProvider } from "@/commons/providers/react-query/react-query.provider";
import React from 'react';

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProvider>
          <ApiUploadProvider>
            <ModalProvider>
              {children}
            </ModalProvider>
          </ApiUploadProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
